/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TorrentIndexImport } from './routes/torrent/index'
import { Route as TorrentTorrentIdImport } from './routes/torrent/$torrentId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TorrentIndexRoute = TorrentIndexImport.update({
  path: '/torrent/',
  getParentRoute: () => rootRoute,
} as any)

const TorrentTorrentIdRoute = TorrentTorrentIdImport.update({
  path: '/torrent/$torrentId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/torrent/$torrentId': {
      preLoaderRoute: typeof TorrentTorrentIdImport
      parentRoute: typeof rootRoute
    }
    '/torrent/': {
      preLoaderRoute: typeof TorrentIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  TorrentTorrentIdRoute,
  TorrentIndexRoute,
])

/* prettier-ignore-end */
