/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TorrentsImport } from './routes/torrents'
import { Route as TorrentImport } from './routes/torrent'
import { Route as IndexImport } from './routes/index'
import { Route as TorrentsIndexImport } from './routes/torrents/index'
import { Route as TorrentInfohashImport } from './routes/torrent/$infohash'

// Create/Update Routes

const TorrentsRoute = TorrentsImport.update({
  path: '/torrents',
  getParentRoute: () => rootRoute,
} as any)

const TorrentRoute = TorrentImport.update({
  path: '/torrent',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TorrentsIndexRoute = TorrentsIndexImport.update({
  path: '/',
  getParentRoute: () => TorrentsRoute,
} as any)

const TorrentInfohashRoute = TorrentInfohashImport.update({
  path: '/$infohash',
  getParentRoute: () => TorrentRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/torrent': {
      id: '/torrent'
      path: '/torrent'
      fullPath: '/torrent'
      preLoaderRoute: typeof TorrentImport
      parentRoute: typeof rootRoute
    }
    '/torrents': {
      id: '/torrents'
      path: '/torrents'
      fullPath: '/torrents'
      preLoaderRoute: typeof TorrentsImport
      parentRoute: typeof rootRoute
    }
    '/torrent/$infohash': {
      id: '/torrent/$infohash'
      path: '/$infohash'
      fullPath: '/torrent/$infohash'
      preLoaderRoute: typeof TorrentInfohashImport
      parentRoute: typeof TorrentImport
    }
    '/torrents/': {
      id: '/torrents/'
      path: '/'
      fullPath: '/torrents/'
      preLoaderRoute: typeof TorrentsIndexImport
      parentRoute: typeof TorrentsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  TorrentRoute: TorrentRoute.addChildren({ TorrentInfohashRoute }),
  TorrentsRoute: TorrentsRoute.addChildren({ TorrentsIndexRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/torrent",
        "/torrents"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/torrent": {
      "filePath": "torrent.tsx",
      "children": [
        "/torrent/$infohash"
      ]
    },
    "/torrents": {
      "filePath": "torrents.tsx",
      "children": [
        "/torrents/"
      ]
    },
    "/torrent/$infohash": {
      "filePath": "torrent/$infohash.tsx",
      "parent": "/torrent"
    },
    "/torrents/": {
      "filePath": "torrents/index.tsx",
      "parent": "/torrents"
    }
  }
}
ROUTE_MANIFEST_END */
