/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/torrents": {
    /**
     * GetTorrents
     * @description controller: downite/handlers.GetTorrents
     */
    get: operations["GET /api/v1/torrents:GetTorrents"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Torrent: {
      /** Format: byte */
      Bitfield?: string;
      DownloadedPieceCount?: number;
      InfoHash?: unknown;
      InfoHashHex?: unknown;
      Length?: number;
      OurPeerId?: unknown;
      Peers?: {
        [key: string]: {
          Address?: {
            Ip?: string;
            Port?: number;
          };
          Country?: string;
          FullAddress?: string;
          Status?: number;
        };
      };
      PieceLength?: number;
      PieceProgresses?: {
          /** Format: byte */
          Buffer?: string;
          DownloadedByteCount?: number;
          Hash?: unknown;
          Index?: number;
          Length?: number;
          RequestedByteCount?: number;
        }[];
      Status?: number;
      TorrentFile?: {
        Announce?: string;
        AnnounceList?: string[][];
        Comment?: string;
        CreatedBy?: string;
        CreationDate?: number;
        Encoding?: string;
        HttpSeeds?: string[];
        Info?: {
          FileLength?: number;
          Name?: string;
          PieceLength?: number;
          /** Format: byte */
          Pieces?: string;
        };
        UrlList?: string[];
      };
      TotalPieceCount?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * GetTorrents
   * @description controller: downite/handlers.GetTorrents
   */
  "GET /api/v1/torrents:GetTorrents": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Torrent"];
        };
      };
      default: {
        content: never;
      };
    };
  };
}
